#!/usr/bin/env python3
"""
S08 - Pluggable Components

Lesson Goal
- Show how to swap chunking and reranking components without rewriting the loop.
- Demonstrate a minimal registry pattern for retrieval pipelines.

Run Examples
```bash
./run.sh s08
./run.sh s08 --chunker sentence --reranker vector_only
./run.sh s08 --input_dir ./your_docs --chunker fixed --chunk_size 400 --overlap 60
```
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Any, Callable

from pymilvus import MilvusClient

from chapters.sample_corpus import SAMPLE_CORPUS
from core import (
    ensure_collection,
    load_embedding_fn,
    read_text,
    search_candidates,
    topk_reranked,
    topk_vector_only,
)


Chunker = Callable[[str], list[str]]
Reranker = Callable[[str, list[dict[str, Any]], int, float], list[dict[str, Any]]]


def chunk_fixed_factory(chunk_size: int, overlap: int) -> Chunker:
    def _chunk(text: str) -> list[str]:
        clean = re.sub(r"\s+", " ", text).strip()
        if not clean:
            return []
        out: list[str] = []
        start = 0
        while start < len(clean):
            end = min(start + chunk_size, len(clean))
            out.append(clean[start:end])
            if end == len(clean):
                break
            start = max(0, end - overlap)
        return out

    return _chunk


def chunk_sentence_like(text: str) -> list[str]:
    clean = re.sub(r"\s+", " ", text).strip()
    if not clean:
        return []
    pieces = [p.strip() for p in re.split(r"(?<=[\.\!\?])\s+", clean) if p.strip()]
    return pieces if pieces else [clean]


def rerank_vector_only(
    question: str, hits: list[dict[str, Any]], topk: int, alpha: float
) -> list[dict[str, Any]]:
    _ = question, alpha
    return topk_vector_only(hits, topk=topk)


def rerank_hybrid(
    question: str, hits: list[dict[str, Any]], topk: int, alpha: float
) -> list[dict[str, Any]]:
    return topk_reranked(question=question, hits=hits, topk=topk, alpha=alpha)


def collect_docs(input_dir: str | None) -> list[dict[str, str]]:
    if input_dir:
        docs: list[dict[str, str]] = []
        base = Path(input_dir)
        for file_path in sorted(base.rglob("*")):
            if not file_path.is_file():
                continue
            if file_path.suffix.lower() not in {".md", ".txt", ".pdf"}:
                continue
            docs.append(
                {
                    "subject": file_path.parent.name or "default",
                    "source": str(file_path.relative_to(base)),
                    "ext": file_path.suffix.lower().lstrip("."),
                    "text": read_text(file_path),
                }
            )
        return docs
    return SAMPLE_CORPUS


def build_records(
    docs: list[dict[str, str]],
    chunker: Chunker,
    embedding_fn: Any,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    next_id = 0
    for doc in docs:
        chunks = chunker(doc.get("text", ""))
        if not chunks:
            continue
        vectors = embedding_fn.encode_documents(chunks)
        for i, chunk in enumerate(chunks):
            rows.append(
                {
                    "id": next_id,
                    "vector": vectors[i],
                    "text": chunk,
                    "source": doc.get("source", "builtin://unknown"),
                    "subject": doc.get("subject", "default"),
                    "ext": doc.get("ext", "txt"),
                    "chunk_idx": i,
                }
            )
            next_id += 1
    return rows


def run(args: argparse.Namespace) -> None:
    if args.chunker == "fixed" and args.overlap >= args.chunk_size:
        raise ValueError("overlap must be smaller than chunk_size for fixed chunker")

    client = MilvusClient(args.db)
    embedding_fn = load_embedding_fn()
    ensure_collection(
        client=client,
        collection_name=args.collection,
        dim=embedding_fn.dim,
        rebuild=args.rebuild,
    )

    chunkers: dict[str, Chunker] = {
        "fixed": chunk_fixed_factory(args.chunk_size, args.overlap),
        "sentence": chunk_sentence_like,
    }
    rerankers: dict[str, Reranker] = {
        "vector_only": rerank_vector_only,
        "hybrid": rerank_hybrid,
    }
    chunker = chunkers[args.chunker]
    reranker = rerankers[args.reranker]

    docs = collect_docs(args.input_dir)
    records = build_records(docs=docs, chunker=chunker, embedding_fn=embedding_fn)
    if not records:
        raise RuntimeError("No records generated by selected chunker and corpus.")
    client.insert(collection_name=args.collection, data=records)
    print(f"Indexed chunks: {len(records)} (chunker={args.chunker})")

    candidates = search_candidates(
        client=client,
        collection_name=args.collection,
        embedding_fn=embedding_fn,
        question=args.question,
        topk=args.topk,
        filter_expr=args.filter,
        candidate_multiplier=args.candidate_multiplier,
    )
    hits = reranker(args.question, candidates, args.topk, args.alpha)

    print(f"\n[S08] chunker={args.chunker} reranker={args.reranker}")
    print(f"Question: {args.question}")
    for i, hit in enumerate(hits, start=1):
        entity = hit.get("entity", {})
        text = (entity.get("text", "") or "").strip()
        preview = text[:160] + ("..." if len(text) > 160 else "")
        print(
            f"[{i}] vector={hit.get('distance', 0):.4f} "
            f"subject={entity.get('subject')} source={entity.get('source')}"
        )
        print(f"    {preview}")


def register_subparser(
    subparsers: argparse._SubParsersAction[argparse.ArgumentParser],
) -> None:
    parser = subparsers.add_parser(
        "s08",
        help="S08: run retrieval with pluggable chunker/reranker components.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--db", default="milvus_demo.db")
    parser.add_argument("--collection", default="kb_collection")
    parser.add_argument("--input_dir", default=None)
    parser.add_argument("--rebuild", action="store_true")
    parser.add_argument("--chunker", choices=["fixed", "sentence"], default="fixed")
    parser.add_argument("--reranker", choices=["vector_only", "hybrid"], default="hybrid")
    parser.add_argument("--chunk_size", type=int, default=500)
    parser.add_argument("--overlap", type=int, default=80)
    parser.add_argument("--question", default="How can I improve retrieval quality and latency?")
    parser.add_argument("--topk", type=int, default=5)
    parser.add_argument("--filter", default=None)
    parser.add_argument("--candidate_multiplier", type=int, default=3)
    parser.add_argument("--alpha", type=float, default=0.75)
    parser.set_defaults(handler=run)
